version: '3'
services:
  postgres:
    container_name: postgres-db
    image: postgres:15.1
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4:6.18
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

  nestjs-api:
    build:
      context: .
      target: install-dependencies
    command: npm run start:dev
    volumes:
      - ./src:/user/src/app/src
    env_file:
      - .env
    ports:
      - '3000:3000'
      - '5555:5555'
      - '9229:9229'
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
volumes:
  postgres-data:
